import '@fontsource-variable/montserrat';
import './assets/css/fonts.css';
import "./globals.css";
import { Container } from '@mui/material';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body><Container>{children}</Container></body>
    </html>
  );
}
